//! `SeaORM` Entities.

pub mod allocations;
pub mod audit_logs;
pub mod benefits;
pub mod devops_events;
pub mod budget_lines;
pub mod event_outbox;
pub mod gate_reviews;
pub mod ideas;
pub mod insight_snapshots;
pub mod merge_records;
pub mod milestones;
pub mod objective_links;
pub mod objectives;
pub mod prelude;
pub mod proposals;
pub mod report_definitions;
pub mod risks;
pub mod scenarios;
pub mod sprint_notes;
pub mod sprints;
pub mod tasks;
pub mod work_item_dependencies;
pub mod work_items;
